"""
Fraud Policy Actions (Policy v1.0)
The 14 allowed actions under the HHGOA fraud investigation policy.
"""

ALLOW_TRANSACTION = "ALLOW_TRANSACTION"
DECLINE_TRANSACTION = "DECLINE_TRANSACTION"
MONITOR_CARD = "MONITOR_CARD"
MONITOR_CONNECTED_CARDS = "MONITOR_CONNECTED_CARDS"
WARN_CUSTOMER = "WARN_CUSTOMER"
VERIFY_WITH_CUSTOMER = "VERIFY_WITH_CUSTOMER"
STEP_UP_AUTH = "STEP_UP_AUTH"
BLOCK_CARD = "BLOCK_CARD"
BLOCK_ALL_CARDS = "BLOCK_ALL_CARDS"
GENERATE_REPORT = "GENERATE_REPORT"
CREATE_CASE = "CREATE_CASE"
FILE_REPORT = "FILE_REPORT"
ESCALATE_TO_ANALYST = "ESCALATE_TO_ANALYST"
CLOSE_NO_FRAUD = "CLOSE_NO_FRAUD"

ALL_ACTIONS = {
    ALLOW_TRANSACTION, DECLINE_TRANSACTION, MONITOR_CARD, MONITOR_CONNECTED_CARDS,
    WARN_CUSTOMER, VERIFY_WITH_CUSTOMER, STEP_UP_AUTH, BLOCK_CARD, BLOCK_ALL_CARDS,
    GENERATE_REPORT, CREATE_CASE, FILE_REPORT, ESCALATE_TO_ANALYST, CLOSE_NO_FRAUD
}
